version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest-lite
    container_name: it-support-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_APP_USER_PASSWORD: ${ORACLE_APP_USER_PASSWORD}
      ORACLE_APP_USER: ${ORACLE_APP_USER}
      ORACLE_HOST: ${ORACLE_HOST}
      ORACLE_PORT: ${ORACLE_PORT}
    volumes:
      - ./DB_Oracle/init_scripts:/opt/oracle/scripts/startup
      - it-support-system-data3:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "bash", "-c", "echo \"SELECT CASE WHEN status = 'OPEN' THEN 'READY' ELSE 'NOT READY' END FROM v\\$pdbs WHERE name = 'FREEPDB1';\" | sqlplus ${ORACLE_APP_USER}/${ORACLE_APP_USER_PASSWORD}@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_PDB} | grep -q 'READY'"]
      interval: 10s
      timeout: 10s
      retries: 1000

  backend-app:
    build: .\Backend\supportticketsystem\  
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_PDB}
      SPRING_DATASOURCE_USERNAME: ${ORACLE_APP_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORACLE_APP_USER_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_USERNAME_PASSWORD: ${ADMIN_USERNAME_PASSWORD}

volumes:
  it-support-system-data3: