-- alter to FREEPDB1
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = APP_USER;

-- Create the Employees table if it doesn't exist
CREATE TABLE Employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(40) CHECK (role IN ('IT_SUPPORT', 'EMPLOYEE'))
);

-- Create the Tickets table if it doesn't exist
CREATE TABLE Tickets (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB NOT NULL,
    priority VARCHAR2(10) CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    status VARCHAR2(20) DEFAULT 'NEW' CHECK (status IN ('NEW', 'IN_PROGRESS', 'RESOLVED')),
    category VARCHAR2(20) CHECK (category IN ('Network', 'Hardware', 'Software','Other')),
    creation_date DATE DEFAULT SYSDATE,
    employee_id NUMBER NOT NULL,
    CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES Employees(employee_id)
);

-- Create the Comments table if it doesn't exist
CREATE TABLE Comments (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    comment_text CLOB NOT NULL,
    comment_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_comment_ticket FOREIGN KEY (ticket_id) REFERENCES Tickets(ticket_id),
    CONSTRAINT fk_comment_employee FOREIGN KEY (employee_id) REFERENCES Employees(employee_id)
);

-- Create the Audit_Log table if it doesn't exist
CREATE TABLE Audit_Log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    action VARCHAR2(50) NOT NULL,
    action_date DATE DEFAULT SYSDATE,
    performed_by NUMBER NOT NULL,
    CONSTRAINT fk_audit_ticket FOREIGN KEY (ticket_id) REFERENCES Tickets(ticket_id),
    CONSTRAINT fk_audit_employee FOREIGN KEY (performed_by) REFERENCES Employees(employee_id)
);

COMMIT;