version: '3.8'
services:
  app:
    build: .\
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_PDB}
      SPRING_DATASOURCE_USERNAME: ${ORACLE_APP_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORACLE_APP_USER_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_USERNAME_PASSWORD: ${ADMIN_USERNAME_PASSWORD}

    networks:
      - shared-network

networks:
  shared-network:
    external: true